server:
  port: 20000

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: application
    password: application
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true