###
GET {{toy-msa-api}}/order-service/health-check

###
POST {{toy-msa-api}}/user-service/users
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "test-user",
  "password": "secure-password"
}

###
POST {{toy-msa-api}}/order-service/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "quantity": 10,
  "unitPrice": 1500,
  "userId": "9c2017e0-bee1-485f-96c8-eaea9cb2d394"
}

###
POST {{toy-msa-api}}/order-service/orders
Content-Type: application/json

{
  "productId": "CATALOG-002",
  "quantity": 20,
  "unitPrice": 1000,
  "userId": "9c2017e0-bee1-485f-96c8-eaea9cb2d394"
}

###
GET {{toy-msa-api}}/order-service/orders?userId=9c2017e0-bee1-485f-96c8-eaea9cb2d394