###
GET {{toy-msa-api}}/user-service/health-check

###
GET {{toy-msa-api}}/user-service/welcome

###
GET http://localhost:8082/actuator

### 회원가입
POST {{toy-msa-api}}/user-service/users
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "test-user",
  "password": "secure-password"
}

### 로그인
POST {{toy-msa-api}}/user-service/login
Content-Type: application/json

{
"email": "test@example.com",
"password": "secure-password"
}

### 사용자 조회
GET {{toy-msa-api}}/user-service/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2OTExMjMxZi0xZDM5LTRkYmUtYjZkNy0yOGRkMTRiNDI3NDEiLCJpYXQiOjE3NzM0ODY4MzksImV4cCI6MTc3MzU3MzIzOX0.fY3lZGd4bhxFDFOiZpCI2_lFjAAF-yu2fAIDG0coyjVtd3LG2bjWQTgOcf6PP4c4WP-lP50mTW7vBVLGNAlDVw

### 서킷브레이커 상태 확인
GET http://localhost:8082/actuator/circuitbreakers

###
GET http://localhost:8082/actuator/circuitbreakerevents
