###
GET {{toy-msa-api}}/user-service/health-check

###
GET {{toy-msa-api}}/user-service/welcome

###
GET http://localhost:8082/actuator

### 회원가입
POST {{toy-msa-api}}/user-service/users
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "test-user",
  "password": "secure-password"
}

### 로그인
POST {{toy-msa-api}}/user-service/login
Content-Type: application/json

{
"email": "test@example.com",
"password": "secure-password"
}

### 사용자 조회
GET {{toy-msa-api}}/user-service/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxYzU5ODM5Ni0zZDJlLTQ4YTYtYjUwYS1kN2YwMWU3ZGNkZDkiLCJpYXQiOjE3NzMxNzY2NjgsImV4cCI6MTc3MzI2MzA2OH0.ACyTkH7_kOhGxKrJ4spUXxHP0oc-MBsg8KWlDoyGvpHhFFuclI8yaoda_iucxAl1zbqt1s7WqgYIIENPDh3dkQ

### 서킷브레이커 상태 확인
POST http://localhost:8082/actuator/circuitbreakers

###
GET http://localhost:8082/actuator/circuitbreakerevents

