server:
  port: 60000

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://127.0.0.1:8888
  cloud:
    config:
      name: ecommerce, user-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  web:
    error:
      include-message: always
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: application
    password: application
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: none

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce.

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh

logging:
  level:
    org.springframework.security: DEBUG
    com.uno.userservice.infrastructure.client: DEBUG