server:
  port: 8000

spring:
  application:
    name: apigateway-service
  profiles:
    default: local
  config:
    import:
      - logging.yml
      - monitoring.yml
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
      loadbalancer:
        mode: service
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway Webflux Global Filter
                preLogger: true
                postLogger: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/login, /user-service/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/actuator/**, /user-service/health-check, /user-service/welcome
                - Method=GET,POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter
            - id: catalog-service
              uri: lb://catalog-service
              predicates:
                - Path=/catalog-service/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order-service/**

eureka:
  client:
    enabled: false

jwt:
  secret: ${JWT_SECRET}

---
spring.config.activate.on-profile: local, test

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: false

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  server:
    port: 8081

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd
