server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /Users/wjsyuwls/workspace/inflearn/git-local-repo
        git: #default
          uri: https://github.com/joneconsulting/spring-cloud-config.git
          default-label: master
#          username: [username]
#          password: [password]